import React from 'react';
import { MarkerType } from 'react-flow-renderer';

export const nodesData2 = [
    {
        id: 'dndnode_0',
        type: 'CustomGroupNode',
        position: {
            x: 50,
            y: -100,
        },
        draggable: true,
        data: {
            label: 'LCS1',
            description: 'Add description',
            bgColor: '#ffe8db',
        },
        style: {
            backgroundColor: '#ffe8db',
            position: 'fixed',
            zIndex: -1,
            width: 400,
            height: 1200,
        },
        width: 400,
        height: 1200,
        selected: false,
        positionAbsolute: {
            x: 50,
            y: -100,
        },
        dragging: false,
    },
    {
        id: 'dndnode_2',
        type: 'CustomNode',
        position: {
            x: 100,
            y: 150,
        },
        draggable: true,
        data: {
            label: 'CustomNode node',
            description: 'Add description',
        },
        style: {
            backgroundColor: '#ffffff',
            width: 212,
            height: 72,
        },
        parentNode: 'dndnode_0',
        extent: 'parent',
        width: 212,
        height: 72,
        selected: false,
        positionAbsolute: {
            x: 150,
            y: 200,
        },
        dragging: false,
    },
    {
        id: 'dndnode_3',
        type: 'CustomGroupNode',
        position: {
            x: 450,
            y: -100,
        },
        draggable: true,
        data: {
            label: 'LCS2',
            description: 'Add description',
            bgColor: '#e5ffff',
        },
        style: {
            backgroundColor: '#e5ffff',
            position: 'fixed',
            zIndex: -1,
            width: 400,
            height: 600,
        },
        width: 400,
        height: 600,
        selected: true,
        positionAbsolute: {
            x: 450,
            y: -100,
        },
        dragging: false,
    },
    {
        id: 'dndnode_4',
        type: 'CustomGroupNode',
        position: {
            x: 450,
            y: 500,
        },
        draggable: true,
        data: {
            label: 'LCS3',
            description: 'Add description',
            bgColor: '#c8ffbd',
        },
        style: {
            backgroundColor: '#c8ffbd',
            position: 'fixed',
            zIndex: -1,
            width: 400,
            height: 600,
        },
        width: 400,
        height: 600,
        selected: false,
        positionAbsolute: {
            x: 450,
            y: 500,
        },
        dragging: false,
    },
    {
        id: 'dndnode_5',
        type: 'CustomGroupNode',
        position: {
            x: 850,
            y: -100,
        },
        draggable: true,
        data: {
            label: 'LCS4',
            description: 'Add description',
            bgColor: '#aea8ff',
        },
        style: {
            backgroundColor: '#aea8ff',
            position: 'fixed',
            zIndex: -1,
            width: 400,
            height: 400,
        },
        width: 400,
        height: 400,
        selected: false,
        positionAbsolute: {
            x: 850,
            y: -100,
        },
        dragging: false,
    },
    {
        id: 'dndnode_6',
        type: 'CustomGroupNode',
        position: {
            x: 850,
            y: 300,
        },
        draggable: true,
        data: {
            label: 'LCS5',
            description: 'Add description',
            bgColor: '#ffcccc',
        },
        style: {
            backgroundColor: '#ffcccc',
            position: 'fixed',
            zIndex: -1,
            width: 400,
            height: 400,
        },
        width: 400,
        height: 400,
        selected: false,
        positionAbsolute: {
            x: 850,
            y: 300,
        },
        dragging: false,
    },
    {
        id: 'dndnode_7',
        type: 'CustomGroupNode',
        position: {
            x: 850,
            y: 700,
        },
        draggable: true,
        data: {
            label: 'LCS6',
            description: 'Add description',
            bgColor: '#ffee99',
        },
        style: {
            backgroundColor: '#ffee99',
            position: 'fixed',
            zIndex: -1,
            width: 400,
            height: 400,
        },
        width: 400,
        height: 400,
        selected: false,
        positionAbsolute: {
            x: 850,
            y: 700,
        },
        dragging: false,
    },
    {
        id: 'dndnode_8',
        type: 'CustomNode',
        position: {
            x: 100,
            y: 350,
        },
        draggable: true,
        data: {
            label: 'CustomNode node',
            description: 'Add description',
        },
        style: {
            backgroundColor: '#ffffff',
            width: 212,
            height: 72,
        },
        parentNode: 'dndnode_0',
        extent: 'parent',
        width: 212,
        height: 72,
        selected: false,
        positionAbsolute: {
            x: 150,
            y: 250,
        },
        dragging: false,
    },
    {
        id: 'dndnode_9',
        type: 'CustomNode',
        position: {
            x: 100,
            y: 200,
        },
        draggable: true,
        data: {
            label: 'CustomNode node',
            description: 'Add description',
        },
        style: {
            backgroundColor: '#ffffff',
            width: 212,
            height: 72,
        },
        parentNode: 'dndnode_3',
        extent: 'parent',
        width: 212,
        height: 72,
        selected: false,
        positionAbsolute: {
            x: 550,
            y: 100,
        },
        dragging: false,
    },
    {
        id: 'dndnode_10',
        type: 'CustomNode',
        position: {
            x: 100,
            y: 150,
        },
        draggable: true,
        data: {
            label: 'CustomNode node',
            description: 'Add description',
        },
        style: {
            backgroundColor: '#ffffff',
            width: 212,
            height: 72,
        },
        parentNode: 'dndnode_6',
        extent: 'parent',
        width: 212,
        height: 72,
        selected: false,
        dragging: false,
        positionAbsolute: {
            x: 950,
            y: 450,
        },
    },
    {
        id: 'dndnode_11',
        type: 'CustomNode',
        position: {
            x: 100,
            y: 600,
        },
        draggable: true,
        data: {
            label: 'CustomNode node',
            description: 'Add description',
        },
        style: {
            backgroundColor: '#ffffff',
            width: 212,
            height: 72,
        },
        parentNode: 'dndnode_0',
        extent: 'parent',
        width: 212,
        height: 72,
        selected: false,
        positionAbsolute: {
            x: 150,
            y: 500,
        },
        dragging: false,
    },
    {
        id: 'dndnode_12',
        type: 'CustomNode',
        position: {
            x: 100,
            y: 200,
        },
        draggable: true,
        data: {
            label: 'CustomNode node',
            description: 'Add description',
        },
        style: {
            backgroundColor: '#ffffff',
            width: 212,
            height: 72,
        },
        parentNode: 'dndnode_4',
        extent: 'parent',
        width: 212,
        height: 72,
        selected: false,
        positionAbsolute: {
            x: 550,
            y: 700,
        },
        dragging: false,
    },
    {
        id: 'dndnode_13',
        type: 'CustomNode',
        position: {
            x: 100,
            y: 200,
        },
        draggable: true,
        data: {
            label: 'CustomNode node',
            description: 'Add description',
        },
        style: {
            backgroundColor: '#ffffff',
            width: 212,
            height: 72,
        },
        parentNode: 'dndnode_7',
        extent: 'parent',
        width: 212,
        height: 72,
        selected: false,
        positionAbsolute: {
            x: 950,
            y: 900,
        },
        dragging: false,
    },
];

export const edgesData2 = [
    {
        source: 'dndnode_9',
        sourceHandle: 'b',
        target: 'dndnode_10',
        targetHandle: null,
        type: 'smoothstep',
        id: 'reactflow__edge-dndnode_9b-dndnode_10',
    },
    {
        source: 'dndnode_9',
        sourceHandle: 'b',
        target: 'dndnode_8',
        targetHandle: null,
        type: 'smoothstep',
        id: 'reactflow__edge-dndnode_9b-dndnode_8',
    },
    {
        source: 'dndnode_11',
        sourceHandle: 'b',
        target: 'dndnode_12',
        targetHandle: null,
        type: 'smoothstep',
        id: 'reactflow__edge-dndnode_11b-dndnode_12',
    },
    {
        source: 'dndnode_12',
        sourceHandle: 'b',
        target: 'dndnode_13',
        targetHandle: null,
        type: 'smoothstep',
        id: 'reactflow__edge-dndnode_12b-dndnode_13',
    },
];
